# Generated by Django 5.1.1 on 2024-09-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('موضوع', models.CharField(max_length=50)),
                ('توضیحات', models.TextField()),
                ('publish_day', models.DateField()),
                ('created_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
            ],
        ),
    ]
