# Generated by Django 5.1.1 on 2024-09-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.TextField(default='sari'),
        ),
        migrations.AddField(
            model_name='post',
            name='آپارتمان',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='بر',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='زمین',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='سند',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='قیمت_هر_متر',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='قیمت_کل',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='متراژ',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='ویلا',
            field=models.BooleanField(default=False),
        ),
    ]
