# Generated by Django 5.1.1 on 2024-09-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_location_post_آپارتمان_post_بر_post_زمین_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='اجاره',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='فروش',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='قیمت_هر_متر',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='قیمت_کل',
            field=models.IntegerField(default=0),
        ),
    ]
